// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/rxode2parse.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rxQs
Rcpp::CharacterVector rxQs(SEXP const x);
RcppExport SEXP _rxode2parse_rxQs(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP const >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rxQs(x));
    return rcpp_result_gen;
END_RCPP
}
// rxQr
SEXP rxQr(const std::string& encoded_string);
RcppExport SEXP _rxode2parse_rxQr(SEXP encoded_stringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type encoded_string(encoded_stringSEXP);
    rcpp_result_gen = Rcpp::wrap(rxQr(encoded_string));
    return rcpp_result_gen;
END_RCPP
}
// rxode2parseSetRstudio
SEXP rxode2parseSetRstudio(bool isRstudio);
RcppExport SEXP _rxode2parse_rxode2parseSetRstudio(SEXP isRstudioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type isRstudio(isRstudioSEXP);
    rcpp_result_gen = Rcpp::wrap(rxode2parseSetRstudio(isRstudio));
    return rcpp_result_gen;
END_RCPP
}
// rxParseSetSilentErr
bool rxParseSetSilentErr(int silent);
RcppExport SEXP _rxode2parse_rxParseSetSilentErr(SEXP silentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type silent(silentSEXP);
    rcpp_result_gen = Rcpp::wrap(rxParseSetSilentErr(silent));
    return rcpp_result_gen;
END_RCPP
}
