.parseEnv$.parseFuns <- c("gammafn", "lgammafn", "lgamma", "loggamma", "digamma", "trigamma", 
"tetragamma", "pentagamma", "cospi", "sinpi", "tanpi", "log1p", 
"expm1", "factorial", "lfactorial", "lgamma1p", "expm1", "log10", 
"log2", "log1pexp", "!", "phi", "pnorm", "normcdf", "qnorm", 
"fabs", "pow", "R_pow", "R_pow_di", "Rx_pow_di", "Rx_pow", "lbeta", 
"==", "!=", ">=", "<=", "<", ">", "&&", "||", "&", "|", "lgamma", 
"abs", "acos", "acosh", "asin", "asinh", "atan", "atan2", "atanh", 
"beta", "cos", "cosh", "erf", "erfc", "exp", "gamma", "linCmtA", 
"linCmtC", "linCmtB", "log", "polygamma", "rxTBS", "rxTBSi", 
"rxTBSd", "rxTBSd2", "sin", "sinh", "sqrt", "tan", "tanh", "gammap", 
"floor", "round", "ceil", "trunc", "bessel_i", "bessel_j", "bessel_k", 
"bessel_y", "logspace_add", "logspace_sub", "fmax2", "fmin2", 
"sign", "fsign", "fprec", "fround", "ftrunc", "transit", "gammaq", 
"gammapDer", "gammapInv", "gammapInva", "gammaqInv", "gammaqInva", 
"lowergamma", "uppergamma", "max", "min", "logit", "expit", "probit", 
"probitInv", "tlast", "tfirst", "lag", "lead", "dose", "podo", 
"dabs", "dabs2", "abs1", "dabs1", "erfinv", "abs0", "dosenum", 
"first", "last", "diff", "is.nan", "is.na", "is.finite", "is.infinite", 
"llikPois", "llikPoisDlambda", "llikBinom", "llikBinomDprob", 
"llikNbinom", "llikNbinomDprob", "llikNbinomMu", "llikNbinomMuDmu", 
"llikBeta", "llikBetaDshape1", "llikBetaDshape2", "llikT", "llikTDdf", 
"llikTDmean", "llikTDsd", "llikChisq", "llikChisqDdf", "llikExp", 
"llikExpDrate", "llikF", "llikFDdf1", "llikFDdf2", "llikGeom", 
"llikGeomDprob", "llikUnif", "llikUnifDalpha", "llikUnifDbeta", 
"llikWeibull", "llikWeibullDshape", "llikWeibullDscale", "llikGamma", 
"llikGammaDshape", "llikGammaDrate", "llikCauchy", "llikCauchyDlocation", 
"llikCauchyDscale", "llikNorm", "llikNormDmean", "llikNormDsd", 
"llikXPois", "llikXPoisDlambda", "llikXBinom", "llikXBinomDprob", 
"llikXNbinomMu", "llikXNbinomMuDmu", "llikXNbinom", "llikXNbinomDprob", 
"llikXBeta", "llikXBetaDshape1", "llikXBetaDshape2", "llikXT", 
"llikXTDdf", "llikXTDmean", "llikXTDsd", "llikXChisq", "llikXChisqDdf", 
"llikXExp", "llikXExpDrate", "llikXF", "llikXFDdf1", "llikXFDdf2", 
"llikXGeom", "llikXGeomDprob", "llikXUnif", "llikXUnifDalpha", 
"llikXUnifDbeta", "llikXWeibull", "llikXWeibullDshape", "llikXWeibullDscale", 
"llikXGamma", "llikXGammaDshape", "llikXGammaDrate", "llikXCauchy", 
"llikXCauchyDlocation", "llikXCauchyDscale", "llikXNorm", "llikXNormDmean", 
"llikXNormDsd", "linCmt", "rnorm", "rxnorm", "rxbinom", "rbinom", 
"rxcauchy", "rcauchy", "rchisq", "rxchisq", "rexp", "rxexp", 
"rbeta", "rxbeta", "rgeom", "rxgeom", "rxpois", "rpois", "rxt", 
"rt")
