# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rxQsParse <- function(x) {
    .Call(`_rxode2parse_rxQsParse`, x)
}

rxQrParse <- function(encoded_string) {
    .Call(`_rxode2parse_rxQrParse`, encoded_string)
}

